from typing import Dict

# 定义多语言消息
MESSAGES: Dict[str, Dict[str, str]] = {
    'en': {
        'config_not_found': "⚠️ Config file config.json not found",
        'creating_example_config': "📝 Creating example config file...",
        'plz_edit_and_restart': "ℹ️ Please edit config.json and restart the program",
        'bot_running_error': "💥 Bot runtime error: {err}",
        'recieced_sig_closing': "🛑 Received signal {sig}, closing...",
        'platform_not_found': "❌ Platform '{platform}' not found or default platform '{default_platform}' configuration missing",
        'back_to_ollama': "🫥 Falling back to built-in Ollama client",
        
        # From core/bot.py
        'bot_initializing': "🥳 Initializing Mesh AI Bot...",
        'ai_client_initialized': "✅ AI client initialized",
        'available_models': "✅ Available AI models: {model_names}",
        'no_models_warning': "⚠️ No available models found, please check service",
        'model_list_failed': "⚠️ Failed to get model list: {error}",
        'meshtastic_connected': "✅ Meshtastic connected, Node ID: {node_id}",
        'node_info_error': "❌ Unable to get Meshtastic node information",
        'meshtastic_connect_failed': "❌ Meshtastic connection failed: {error}",
        'connection_established': "🔗 Mesh device connection established",
        'event_loop_not_running': "⚠️ Event loop not running, unable to process messages",
        'message_queued': "📩 Message queued, from: {sender}",
        'queue_failed': "❌ Message queue failed: {error}",
        'queue_processing_error': "❌ Message queue processing error: {error}",
        'bot_started': "🚀 Mesh AI Bot started, press Ctrl+C to exit...",
        'interrupt_received': "🛑 Interrupt received, closing...",
        'bot_shutting_down': "🔧 Shutting down Mesh AI Bot...",
        'meshtastic_closed': "🔌 Meshtastic connection closed",
        'ai_client_closed': "🧠 AI client closed",
        'processing_message': "🔍 Processing message from {sender}",
        'sending_response': "📤 Sending response to {target}",
        'response_sent': "✅ Response sent successfully",
        'send_failed': "❌ Message send failed: {error}",
        'lock_acquired': "🔒 Processing lock acquired",
        'lock_released': "🔓 Processing lock released",
        
        # message_processor.py
        'packet_missing_decoded': "⚠️ Packet missing 'decoded' field",
        'node_name': "👤 Node {node_id} name: {long_name}",
        'node_info_type_warning': "⚠️ Node {node_id} info is not dictionary type",
        'broadcast_message_received': "📢 Broadcast from {from_id}{name_info}: {short_text}",
        'private_message_received': "📩 Private message from {from_id}{name_info}: {short_text}",
        'rssi_debug': "📶 RSSI: {rssi} dBm",
        'snr_debug': "🔊 SNR: {snr} dB",
        'position_received': "📍 Position received from {from_id}",
        'detailed_position': "Detailed position: {lat:.6f}, {lon:.6f}",
        'missing_from_field': "❌ Missing 'from' field",
        'position_data_empty': "⚠️ Position data empty",
        'missing_lat_lon': "❌ Missing latitude/longitude",
        'mention_detected': "🎯 Mention detected, will reply to broadcast",
        'question_detected': "❓ Question detected, will reply to broadcast",
        'keyword_detected': "🔍 Keyword '{keyword}' detected, will reply to broadcast",
        'ignore_broadcast': "⏭️ Ignoring broadcast (no reply condition triggered)",
        'ai_broadcast_response': "🤖 AI broadcast response: {response}",
        'ai_private_response': "🤖 AI private response: {response}",
        'ai_processing_failed': "❌ AI processing failed: {error_msg}",
        'message_processing_error': "❌ Message processing error: {error}",
        'broadcast_settings_updated': "🔄 Broadcast message processing: {status}",
        'keywords_updated': "🔄 Updated broadcast trigger keywords: {keywords}",
        'processing_failed': "❌ Processing failed: {error_msg}",
        'processing_exception': "❌ Processing exception, please try again later",
        'unknown': "Unknown",
        'unknown_type': "Unknown type",
        'unknown_error': "Unknown error",
        'enabled': "Enabled",
        'disabled': "Disabled",
        'other_message': "Another message"
    },
    'zh_CN': {
        'config_not_found': "⚠️ 未找到 config.json 配置文件",
        'creating_example_config': "📝 正在创建示例配置文件...",
        'plz_edit_and_restart': "ℹ️ 请编辑 config.json 文件并重新启动程序",
        'bot_running_error': "💥 机器人运行异常: {err}",
        'recieced_sig_closing': "🛑 收到信号 {sig}，正在关闭...",
        'platform_not_found': "❌未找到平台 '{platform}' 或默认平台 '{default_platform}' 的配置",
        'back_to_ollama': "🫥回退到内置 Ollama 客户端",
        
        # 从 core/bot.py 中提取的翻译键
        'bot_initializing': "🥳正在初始化 Mesh AI 机器人...",
        'ai_client_initialized': "✅ AI 客户端初始化完成",
        'available_models': "✅ 可用 AI 模型: {model_names}",
        'no_models_warning': "⚠️ 未找到可用模型，请检查服务",
        'model_list_failed': "⚠️ 获取模型列表失败: {error}",
        'meshtastic_connected': "✅ Meshtastic 连接成功，节点 ID: {node_id}",
        'node_info_error': "❌ 无法获取 Meshtastic 节点信息",
        'meshtastic_connect_failed': "❌ Meshtastic 连接失败: {error}",
        'connection_established': "🔗 Mesh 设备连接已建立",
        'event_loop_not_running': "⚠️ 事件循环未运行，无法处理消息",
        'message_queued': "📩 消息已入队，来自: {sender}",
        'queue_failed': "❌ 消息入队失败: {error}",
        'queue_processing_error': "❌ 消息队列处理异常: {error}",
        'bot_started': "🚀 Mesh AI 机器人已启动，按 Ctrl+C 退出...",
        'interrupt_received': "🛑 收到中断信号，正在关闭...",
        'bot_shutting_down': "🔧 正在关闭 Mesh AI 机器人...",
        'meshtastic_closed': "🔌 Meshtastic 连接已关闭",
        'ai_client_closed': "🧠 AI 客户端已关闭",
        'processing_message': "🔍 正在处理来自 {sender} 的消息",
        'sending_response': "📤 正在发送回复到 {target}",
        'response_sent': "✅ 回复发送成功",
        'send_failed': "❌ 消息发送失败: {error}",
        'lock_acquired': "🔒 获取处理锁",
        'lock_released': "🔓 释放处理锁",
        # message_processor.py
        'packet_missing_decoded': "⚠️ 数据包缺少 'decoded' 字段",
        'node_name': "👤 节点 {node_id} 名称: {long_name}",
        'node_info_type_warning': "⚠️ 节点 {node_id} 信息非字典类型",
        'broadcast_message_received': "📢 群发 来自 {from_id}{name_info}: {short_text}",
        'private_message_received': "📩 私聊 来自 {from_id}{name_info}: {short_text}",
        'rssi_debug': "📶 RSSI: {rssi} dBm",
        'snr_debug': "🔊 SNR: {snr} dB",
        'position_received': "📍 收到 {from_id} 的位置信息",
        'detailed_position': "详细位置: {lat:.6f}, {lon:.6f}",
        'missing_from_field': "❌ 缺少 'from' 字段",
        'position_data_empty': "⚠️ 位置数据为空",
        'missing_lat_lon': "❌ 缺失经纬度",
        'mention_detected': "🎯 检测到提及，将回复群发消息",
        'question_detected': "❓ 检测到问题，将回复群发消息",
        'keyword_detected': "🔍 检测到关键词 '{keyword}'，将回复群发消息",
        'ignore_broadcast': "⏭️  忽略群发消息（未触发回复条件）",
        'ai_broadcast_response': "🤖 AI 回复群发消息: {response}",
        'ai_private_response': "🤖 AI 回复私聊消息: {response}",
        'ai_processing_failed': "❌ AI 处理失败: {error_msg}",
        'message_processing_error': "❌ 消息处理异常: {error}",
        'broadcast_settings_updated': "🔄 群发消息处理: {status}",
        'keywords_updated': "🔄 更新群发触发关键词: {keywords}",
        'processing_failed': "❌ 处理失败: {error_msg}",
        'processing_exception': "❌ 处理异常，请稍后重试",
        'unknown': "未知",
        'unknown_type': "未知类型",
        'unknown_error': "未知错误",
        'enabled': "启用",
        'disabled': "禁用",
        'other_message': "Another message"
    },
    'es': {
        'config_not_found': "⚠️ Archivo de configuración config.json no encontrado",
        'creating_example_config': "📝 Creando archivo de configuración de ejemplo...",
        'plz_edit_and_restart': "ℹ️ Por favor edita config.json y reinicia el programa",
        'bot_running_error': "💥 Error de ejecución del bot: {err}",
        'recieced_sig_closing': "🛑 Señal {sig} recibida, cerrando...",
        'platform_not_found': "❌ No se encontró la configuración para la plataforma '{platform}' ni para la plataforma predeterminada '{default_platform}'",
        'back_to_ollama': "🫥 Volviendo al cliente Ollama integrado",

        'bot_initializing': "🥳 Inicializando el bot Mesh AI...",
        'ai_client_initialized': "✅ Cliente de IA inicializado",
        'available_models': "✅ Modelos de IA disponibles: {model_names}",
        'no_models_warning': "⚠️ No se encontraron modelos disponibles, verifica el servicio",
        'model_list_failed': "⚠️ Falló al obtener la lista de modelos: {error}",
        'meshtastic_connected': "✅ Conexión a Meshtastic exitosa, ID de nodo: {node_id}",
        'node_info_error': "❌ No se pudo obtener la información del nodo Meshtastic",
        'meshtastic_connect_failed': "❌ Falló la conexión a Meshtastic: {error}",
        'connection_established': "🔗 Conexión al dispositivo Mesh establecida",
        'event_loop_not_running': "⚠️ El bucle de eventos no está en ejecución, no se pueden procesar mensajes",
        'message_queued': "📩 Mensaje encolado, de: {sender}",
        'queue_failed': "❌ Falló al encolar mensaje: {error}",
        'queue_processing_error': "❌ Excepción al procesar la cola de mensajes: {error}",
        'bot_started': "🚀 Bot Mesh AI iniciado, presiona Ctrl+C para salir...",
        'interrupt_received': "🛑 Señal de interrupción recibida, cerrando...",
        'bot_shutting_down': "🔧 Apagando el bot Mesh AI...",
        'meshtastic_closed': "🔌 Conexión a Meshtastic cerrada",
        'ai_client_closed': "🧠 Cliente de IA cerrado",
        'processing_message': "🔍 Procesando mensaje de {sender}",
        'sending_response': "📤 Enviando respuesta a {target}",
        'response_sent': "✅ Respuesta enviada con éxito",
        'send_failed': "❌ Falló el envío del mensaje: {error}",
        'lock_acquired': "🔒 Bloqueo de procesamiento adquirido",
        'lock_released': "🔓 Bloqueo de procesamiento liberado",

        'packet_missing_decoded': "⚠️ El paquete carece del campo 'decoded'",
        'node_name': "👤 Nodo {node_id} nombre: {long_name}",
        'node_info_type_warning': "⚠️ La información del nodo {node_id} no es de tipo diccionario",
        'broadcast_message_received': "📢 Mensaje grupal de {from_id}{name_info}: {short_text}",
        'private_message_received': "📩 Mensaje privado de {from_id}{name_info}: {short_text}",
        'rssi_debug': "📶 RSSI: {rssi} dBm",
        'snr_debug': "🔊 SNR: {snr} dB",
        'position_received': "📍 Recibida ubicación de {from_id}",
        'detailed_position': "Ubicación detallada: {lat:.6f}, {lon:.6f}",
        'missing_from_field': "❌ Falta el campo 'from'",
        'position_data_empty': "⚠️ Datos de posición vacíos",
        'missing_lat_lon': "❌ Faltan latitud y longitud",
        'mention_detected': "🎯 Mención detectada, responderá al mensaje grupal",
        'question_detected': "❓ Pregunta detectada, responderá al mensaje grupal",
        'keyword_detected': "🔍 Palabra clave '{keyword}' detectada, responderá al mensaje grupal",
        'ignore_broadcast': "⏭️ Ignorando mensaje grupal (condiciones de respuesta no cumplidas)",
        'ai_broadcast_response': "🤖 Respuesta IA a mensaje grupal: {response}",
        'ai_private_response': "🤖 Respuesta IA a mensaje privado: {response}",
        'ai_processing_failed': "❌ Falló el procesamiento por IA: {error_msg}",
        'message_processing_error': "❌ Excepción al procesar mensaje: {error}",
        'broadcast_settings_updated': "🔄 Configuración de mensajes grupales: {status}",
        'keywords_updated': "🔄 Palabras clave actualizadas: {keywords}",
        'processing_failed': "❌ Falló el procesamiento: {error_msg}",
        'processing_exception': "❌ Excepción durante el procesamiento, inténtalo más tarde",
        'unknown': "Desconocido",
        'unknown_type': "Tipo desconocido",
        'unknown_error': "Error desconocido",
        'enabled': "Habilitado",
        'disabled': "Deshabilitado",
        'other_message': "Otro mensaje"
    },
    'fr': {
        'config_not_found': "⚠️ Fichier de configuration config.json introuvable",
        'creating_example_config': "📝 Création du fichier de configuration exemple...",
        'plz_edit_and_restart': "ℹ️ Veuillez modifier config.json et redémarrer le programme",
        'bot_running_error': "💥 Erreur d'exécution du bot : {err}",
        'recieced_sig_closing': "🛑 Signal {sig} reçu, fermeture...",
        'platform_not_found': "❌ Configuration introuvable pour la plateforme « {platform} » ou la plateforme par défaut « {default_platform} »",
        'back_to_ollama': "🫥 Retour au client Ollama intégré",

        'bot_initializing': "🥳 Initialisation du bot Mesh AI...",
        'ai_client_initialized': "✅ Client IA initialisé",
        'available_models': "✅ Modèles IA disponibles : {model_names}",
        'no_models_warning': "⚠️ Aucun modèle disponible trouvé, vérifiez le service",
        'model_list_failed': "⚠️ Échec de la récupération de la liste des modèles : {error}",
        'meshtastic_connected': "✅ Connexion à Meshtastic réussie, ID du nœud : {node_id}",
        'node_info_error': "❌ Impossible d’obtenir les informations du nœud Meshtastic",
        'meshtastic_connect_failed': "❌ Échec de la connexion à Meshtastic : {error}",
        'connection_established': "🔗 Connexion à l’appareil Mesh établie",
        'event_loop_not_running': "⚠️ La boucle d’événements n’est pas active, impossible de traiter les messages",
        'message_queued': "📩 Message mis en file d’attente, provenant de : {sender}",
        'queue_failed': "❌ Échec de la mise en file d’attente du message : {error}",
        'queue_processing_error': "❌ Exception lors du traitement de la file d’attente : {error}",
        'bot_started': "🚀 Bot Mesh AI démarré, appuyez sur Ctrl+C pour quitter...",
        'interrupt_received': "🛑 Signal d’interruption reçu, fermeture en cours...",
        'bot_shutting_down': "🔧 Arrêt du bot Mesh AI...",
        'meshtastic_closed': "🔌 Connexion à Meshtastic fermée",
        'ai_client_closed': "🧠 Client IA fermé",
        'processing_message': "🔍 Traitement du message de {sender}",
        'sending_response': "📤 Envoi de la réponse à {target}",
        'response_sent': "✅ Réponse envoyée avec succès",
        'send_failed': "❌ Échec de l’envoi du message : {error}",
        'lock_acquired': "🔒 Verrou de traitement acquis",
        'lock_released': "🔓 Verrou de traitement libéré",

        'packet_missing_decoded': "⚠️ Paquet sans champ « decoded »",
        'node_name': "👤 Nœud {node_id} nom : {long_name}",
        'node_info_type_warning': "⚠️ Les informations du nœud {node_id} ne sont pas de type dictionnaire",
        'broadcast_message_received': "📢 Message diffusé de {from_id}{name_info} : {short_text}",
        'private_message_received': "📩 Message privé de {from_id}{name_info} : {short_text}",
        'rssi_debug': "📶 RSSI : {rssi} dBm",
        'snr_debug': "🔊 SNR : {snr} dB",
        'position_received': "📍 Position reçue de {from_id}",
        'detailed_position': "Position détaillée : {lat:.6f}, {lon:.6f}",
        'missing_from_field': "❌ Champ « from » manquant",
        'position_data_empty': "⚠️ Données de position vides",
        'missing_lat_lon': "❌ Latitude et longitude manquantes",
        'mention_detected': "🎯 Mention détectée, réponse au message diffusé",
        'question_detected': "❓ Question détectée, réponse au message diffusé",
        'keyword_detected': "🔍 Mot-clé « {keyword} » détecté, réponse au message diffusé",
        'ignore_broadcast': "⏭️ Message diffusé ignoré (conditions non remplies)",
        'ai_broadcast_response': "🤖 Réponse IA au message diffusé : {response}",
        'ai_private_response': "🤖 Réponse IA au message privé : {response}",
        'ai_processing_failed': "❌ Échec du traitement par IA : {error_msg}",
        'message_processing_error': "❌ Exception lors du traitement du message : {error}",
        'broadcast_settings_updated': "🔄 Paramètres des messages diffusés : {status}",
        'keywords_updated': "🔄 Mots-clés mis à jour : {keywords}",
        'processing_failed': "❌ Échec du traitement : {error_msg}",
        'processing_exception': "❌ Exception pendant le traitement, veuillez réessayer plus tard",
        'unknown': "Inconnu",
        'unknown_type': "Type inconnu",
        'unknown_error': "Erreur inconnue",
        'enabled': "Activé",
        'disabled': "Désactivé",
        'other_message': "Un autre message"
    },
    'de': {
        'config_not_found': "⚠️ Konfigurationsdatei config.json nicht gefunden",
        'creating_example_config': "📝 Erstelle Beispiel-Konfigurationsdatei...",
        'plz_edit_and_restart': "ℹ️ Bitte config.json bearbeiten und Programm neu starten",
        'bot_running_error': "💥 Bot-Laufzeitfehler: {err}",
        'recieced_sig_closing': "🛑 Signal {sig} empfangen, wird geschlossen...",
        'platform_not_found': "❌ Keine Konfiguration für Plattform '{platform}' oder Standardplattform '{default_platform}' gefunden",
        'back_to_ollama': "🫥 Zurück zum integrierten Ollama-Client",

        'bot_initializing': "🥳 Initialisiere Mesh AI Bot...",
        'ai_client_initialized': "✅ KI-Client initialisiert",
        'available_models': "✅ Verfügbare KI-Modelle: {model_names}",
        'no_models_warning': "⚠️ Keine verfügbaren Modelle gefunden, bitte Dienst prüfen",
        'model_list_failed': "⚠️ Abruf der Modellliste fehlgeschlagen: {error}",
        'meshtastic_connected': "✅ Meshtastic-Verbindung erfolgreich, Knoten-ID: {node_id}",
        'node_info_error': "❌ Knoteninformationen von Meshtastic konnten nicht abgerufen werden",
        'meshtastic_connect_failed': "❌ Meshtastic-Verbindung fehlgeschlagen: {error}",
        'connection_established': "🔗 Mesh-Geräteverbindung hergestellt",
        'event_loop_not_running': "⚠️ Ereignisschleife läuft nicht, Nachrichten können nicht verarbeitet werden",
        'message_queued': "📩 Nachricht in Warteschlange, von: {sender}",
        'queue_failed': "❌ Nachricht konnte nicht in Warteschlange gestellt werden: {error}",
        'queue_processing_error': "❌ Fehler bei der Verarbeitung der Nachrichtenwarteschlange: {error}",
        'bot_started': "🚀 Mesh AI Bot gestartet, Drücke Strg+C zum Beenden...",
        'interrupt_received': "🛑 Unterbrechungssignal empfangen, wird beendet...",
        'bot_shutting_down': "🔧 Mesh AI Bot wird heruntergefahren...",
        'meshtastic_closed': "🔌 Meshtastic-Verbindung geschlossen",
        'ai_client_closed': "🧠 KI-Client geschlossen",
        'processing_message': "🔍 Verarbeite Nachricht von {sender}",
        'sending_response': "📤 Sende Antwort an {target}",
        'response_sent': "✅ Antwort erfolgreich gesendet",
        'send_failed': "❌ Nachricht konnte nicht gesendet werden: {error}",
        'lock_acquired': "🔒 Verarbeitungssperre erworben",
        'lock_released': "🔓 Verarbeitungssperre freigegeben",

        'packet_missing_decoded': "⚠️ Paket enthält kein 'decoded'-Feld",
        'node_name': "👤 Knoten {node_id} Name: {long_name}",
        'node_info_type_warning': "⚠️ Knoteninformationen für {node_id} sind kein Wörterbuch",
        'broadcast_message_received': "📢 Broadcast-Nachricht von {from_id}{name_info}: {short_text}",
        'private_message_received': "📩 Private Nachricht von {from_id}{name_info}: {short_text}",
        'rssi_debug': "📶 RSSI: {rssi} dBm",
        'snr_debug': "🔊 SNR: {snr} dB",
        'position_received': "📍 Standortdaten von {from_id} empfangen",
        'detailed_position': "Detaillierter Standort: {lat:.6f}, {lon:.6f}",
        'missing_from_field': "❌ Feld 'from' fehlt",
        'position_data_empty': "⚠️ Standortdaten leer",
        'missing_lat_lon': "❌ Breiten- und Längengrad fehlen",
        'mention_detected': "🎯 Erwähnung erkannt, antworte auf Broadcast",
        'question_detected': "❓ Frage erkannt, antworte auf Broadcast",
        'keyword_detected': "🔍 Stichwort '{keyword}' erkannt, antworte auf Broadcast",
        'ignore_broadcast': "⏭️ Broadcast ignoriert (Antwortbedingungen nicht erfüllt)",
        'ai_broadcast_response': "🤖 KI-Antwort auf Broadcast: {response}",
        'ai_private_response': "🤖 KI-Antwort auf private Nachricht: {response}",
        'ai_processing_failed': "❌ KI-Verarbeitung fehlgeschlagen: {error_msg}",
        'message_processing_error': "❌ Fehler bei der Nachrichtenverarbeitung: {error}",
        'broadcast_settings_updated': "🔄 Broadcast-Einstellungen: {status}",
        'keywords_updated': "🔄 Auslösende Stichwörter aktualisiert: {keywords}",
        'processing_failed': "❌ Verarbeitung fehlgeschlagen: {error_msg}",
        'processing_exception': "❌ Verarbeitungsfehler – bitte später erneut versuchen",
        'unknown': "Unbekannt",
        'unknown_type': "Unbekannter Typ",
        'unknown_error': "Unbekannter Fehler",
        'enabled': "Aktiviert",
        'disabled': "Deaktiviert",
        'other_message': "Eine andere Nachricht"
    },
    'ja': {
        'config_not_found': "⚠️ 設定ファイル config.json が見つかりません",
        'creating_example_config': "📝 サンプル設定ファイルを作成中...",
        'plz_edit_and_restart': "ℹ️ config.json を編集してプログラムを再起動してください",
        'bot_running_error': "💥 ボット実行エラー: {err}",
        'recieced_sig_closing': "🛑 信号 {sig} を受信、終了中...",
        'platform_not_found': "❌ プラットフォーム '{platform}' またはデフォルトプラットフォーム '{default_platform}' の設定が見つかりません",
        'back_to_ollama': "🫥 組み込みの Ollama クライアントに戻ります",

        'bot_initializing': "🥳 Mesh AI ボットを初期化中...",
        'ai_client_initialized': "✅ AIクライアントが初期化されました",
        'available_models': "✅ 利用可能なAIモデル: {model_names}",
        'no_models_warning': "⚠️ 利用可能なモデルが見つかりません。サービスを確認してください",
        'model_list_failed': "⚠️ モデル一覧の取得に失敗しました: {error}",
        'meshtastic_connected': "✅ Meshtastic 接続成功、ノードID: {node_id}",
        'node_info_error': "❌ Meshtastic ノード情報の取得に失敗しました",
        'meshtastic_connect_failed': "❌ Meshtastic 接続失敗: {error}",
        'connection_established': "🔗 Mesh デバイスとの接続が確立されました",
        'event_loop_not_running': "⚠️ イベントループが実行されておらず、メッセージを処理できません",
        'message_queued': "📩 メッセージをキューに追加しました。送信元: {sender}",
        'queue_failed': "❌ メッセージのキューイングに失敗しました: {error}",
        'queue_processing_error': "❌ メッセージキュー処理中に例外が発生しました: {error}",
        'bot_started': "🚀 Mesh AI ボットが起動しました、Ctrl+Cで終了...",
        'interrupt_received': "🛑 割り込みシグナルを受信、シャットダウン中...",
        'bot_shutting_down': "🔧 Mesh AI ボットをシャットダウン中...",
        'meshtastic_closed': "🔌 Meshtastic 接続を閉じました",
        'ai_client_closed': "🧠 AIクライアントを閉じました",
        'processing_message': "🔍 {sender} からのメッセージを処理中",
        'sending_response': "📤 {target} へ返信を送信中",
        'response_sent': "✅ 返信を送信しました",
        'send_failed': "❌ メッセージ送信に失敗しました: {error}",
        'lock_acquired': "🔒 処理ロックを取得しました",
        'lock_released': "🔓 処理ロックを解放しました",

        'packet_missing_decoded': "⚠️ パケットに 'decoded' フィールドがありません",
        'node_name': "👤 ノード {node_id} 名前: {long_name}",
        'node_info_type_warning': "⚠️ ノード {node_id} の情報が辞書型ではありません",
        'broadcast_message_received': "📢 全体向けメッセージ 受信元 {from_id}{name_info}: {short_text}",
        'private_message_received': "📩 個別メッセージ 受信元 {from_id}{name_info}: {short_text}",
        'rssi_debug': "📶 RSSI: {rssi} dBm",
        'snr_debug': "🔊 SNR: {snr} dB",
        'position_received': "📍 {from_id} の位置情報を受信しました",
        'detailed_position': "詳細な位置情報: {lat:.6f}, {lon:.6f}",
        'missing_from_field': "❌ 'from' フィールドがありません",
        'position_data_empty': "⚠️ 位置情報データが空です",
        'missing_lat_lon': "❌ 緯度・経度が不足しています",
        'mention_detected': "🎯 メンションを検出、全体向けメッセージに返信します",
        'question_detected': "❓ 質問を検出、全体向けメッセージに返信します",
        'keyword_detected': "🔍 キーワード '{keyword}' を検出、全体向けメッセージに返信します",
        'ignore_broadcast': "⏭️ 全体向けメッセージを無視（返信条件未達）",
        'ai_broadcast_response': "🤖 AIが全体向けメッセージに返信: {response}",
        'ai_private_response': "🤖 AIが個別メッセージに返信: {response}",
        'ai_processing_failed': "❌ AI処理に失敗しました: {error_msg}",
        'message_processing_error': "❌ メッセージ処理中にエラーが発生しました: {error}",
        'broadcast_settings_updated': "🔄 全体向けメッセージ処理: {status}",
        'keywords_updated': "🔄 全体向けトリガーキーワードを更新: {keywords}",
        'processing_failed': "❌ 処理に失敗しました: {error_msg}",
        'processing_exception': "❌ 処理中に例外が発生しました。しばらくしてから再試行してください",
        'unknown': "不明",
        'unknown_type': "不明なタイプ",
        'unknown_error': "不明なエラー",
        'enabled': "有効",
        'disabled': "無効",
        'other_message': "その他のメッセージ"
    },
    'ko': {
        'config_not_found': "⚠️ 설정 파일 config.json을 찾을 수 없습니다",
        'creating_example_config': "📝 예제 설정 파일 생성 중...",
        'plz_edit_and_restart': "ℹ️ config.json을 편집하고 프로그램을 재시작하세요",
        'bot_running_error': "💥 봇 실행 오류: {err}",
        'recieced_sig_closing': "🛑 {sig} 신호 수신, 종료 중...",
        'platform_not_found': "❌ 플랫폼 '{platform}' 또는 기본 플랫폼 '{default_platform}'에 대한 설정을 찾을 수 없습니다",
        'back_to_ollama': "🫥 내장된 Ollama 클라이언트로 되돌아갑니다",

        'bot_initializing': "🥳 Mesh AI 봇 초기화 중...",
        'ai_client_initialized': "✅ AI 클라이언트가 초기화되었습니다",
        'available_models': "✅ 사용 가능한 AI 모델: {model_names}",
        'no_models_warning': "⚠️ 사용 가능한 모델을 찾을 수 없습니다. 서비스를 확인하세요",
        'model_list_failed': "⚠️ 모델 목록 가져오기 실패: {error}",
        'meshtastic_connected': "✅ Meshtastic 연결 성공, 노드 ID: {node_id}",
        'node_info_error': "❌ Meshtastic 노드 정보를 가져올 수 없습니다",
        'meshtastic_connect_failed': "❌ Meshtastic 연결 실패: {error}",
        'connection_established': "🔗 Mesh 장치 연결이 설정되었습니다",
        'event_loop_not_running': "⚠️ 이벤트 루프가 실행되지 않아 메시지를 처리할 수 없습니다",
        'message_queued': "📩 메시지가 대기열에 추가됨, 발신자: {sender}",
        'queue_failed': "❌ 메시지 대기열 추가 실패: {error}",
        'queue_processing_error': "❌ 메시지 대기열 처리 중 예외 발생: {error}",
        'bot_started': "🚀 Mesh AI 봇이 시작되었습니다, Ctrl+C로 종료...",
        'interrupt_received': "🛑 인터럽트 신호 수신, 종료 중...",
        'bot_shutting_down': "🔧 Mesh AI 봇을 종료하는 중...",
        'meshtastic_closed': "🔌 Meshtastic 연결이 닫혔습니다",
        'ai_client_closed': "🧠 AI 클라이언트가 닫혔습니다",
        'processing_message': "🔍 {sender}의 메시지 처리 중",
        'sending_response': "📤 {target}에게 응답 전송 중",
        'response_sent': "✅ 응답 전송 성공",
        'send_failed': "❌ 메시지 전송 실패: {error}",
        'lock_acquired': "🔒 처리 잠금 획득",
        'lock_released': "🔓 처리 잠금 해제",

        'packet_missing_decoded': "⚠️ 패킷에 'decoded' 필드가 없습니다",
        'node_name': "👤 노드 {node_id} 이름: {long_name}",
        'node_info_type_warning': "⚠️ 노드 {node_id} 정보가 딕셔너리 유형이 아닙니다",
        'broadcast_message_received': "📢 전체 메시지 수신, 발신자 {from_id}{name_info}: {short_text}",
        'private_message_received': "📩 개인 메시지 수신, 발신자 {from_id}{name_info}: {short_text}",
        'rssi_debug': "📶 RSSI: {rssi} dBm",
        'snr_debug': "🔊 SNR: {snr} dB",
        'position_received': "📍 {from_id}의 위치 정보 수신",
        'detailed_position': "상세 위치: {lat:.6f}, {lon:.6f}",
        'missing_from_field': "❌ 'from' 필드 누락",
        'position_data_empty': "⚠️ 위치 데이터가 비어 있음",
        'missing_lat_lon': "❌ 위도/경도 누락",
        'mention_detected': "🎯 멘션 감지됨, 전체 메시지에 응답합니다",
        'question_detected': "❓ 질문 감지됨, 전체 메시지에 응답합니다",
        'keyword_detected': "🔍 키워드 '{keyword}' 감지됨, 전체 메시지에 응답합니다",
        'ignore_broadcast': "⏭️ 전체 메시지 무시됨(응답 조건 미충족)",
        'ai_broadcast_response': "🤖 AI 전체 메시지 응답: {response}",
        'ai_private_response': "🤖 AI 개인 메시지 응답: {response}",
        'ai_processing_failed': "❌ AI 처리 실패: {error_msg}",
        'message_processing_error': "❌ 메시지 처리 중 오류 발생: {error}",
        'broadcast_settings_updated': "🔄 전체 메시지 처리: {status}",
        'keywords_updated': "🔄 전체 메시지 트리거 키워드 업데이트됨: {keywords}",
        'processing_failed': "❌ 처리 실패: {error_msg}",
        'processing_exception': "❌ 처리 중 예외 발생, 잠시 후 다시 시도하세요",
        'unknown': "알 수 없음",
        'unknown_type': "알 수 없는 유형",
        'unknown_error': "알 수 없는 오류",
        'enabled': "활성화",
        'disabled': "비활성화",
        'other_message': "다른 메시지"
    },
    'ru': {
        'config_not_found': "⚠️ Файл конфигурации config.json не найден",
        'creating_example_config': "📝 Создание примерного файла конфигурации...",
        'plz_edit_and_restart': "ℹ️ Отредактируйте config.json и перезапустите программу",
        'bot_running_error': "💥 Ошибка выполнения бота: {err}",
        'recieced_sig_closing': "🛑 Получен сигнал {sig}, закрытие...",
        'platform_not_found': "❌ Не найдена конфигурация для платформы '{platform}' или платформы по умолчанию '{default_platform}'",
        'back_to_ollama': "🫥 Возврат к встроенному клиенту Ollama",

        'bot_initializing': "🥳 Инициализация бота Mesh AI...",
        'ai_client_initialized': "✅ Клиент ИИ инициализирован",
        'available_models': "✅ Доступные модели ИИ: {model_names}",
        'no_models_warning': "⚠️ Доступные модели не найдены, проверьте службу",
        'model_list_failed': "⚠️ Не удалось получить список моделей: {error}",
        'meshtastic_connected': "✅ Подключение к Meshtastic успешно, ID узла: {node_id}",
        'node_info_error': "❌ Не удалось получить информацию об узле Meshtastic",
        'meshtastic_connect_failed': "❌ Не удалось подключиться к Meshtastic: {error}",
        'connection_established': "🔗 Подключение к устройству Mesh установлено",
        'event_loop_not_running': "⚠️ Цикл событий не запущен, невозможно обрабатывать сообщения",
        'message_queued': "📩 Сообщение добавлено в очередь, от: {sender}",
        'queue_failed': "❌ Не удалось добавить сообщение в очередь: {error}",
        'queue_processing_error': "❌ Ошибка при обработке очереди сообщений: {error}",
        'bot_started': "🚀 Бот Mesh AI запущен, нажмите Ctrl+C для выхода...",
        'interrupt_received': "🛑 Получен сигнал прерывания, завершение работы...",
        'bot_shutting_down': "🔧 Завершение работы бота Mesh AI...",
        'meshtastic_closed': "🔌 Подключение к Meshtastic закрыто",
        'ai_client_closed': "🧠 Клиент ИИ закрыт",
        'processing_message': "🔍 Обработка сообщения от {sender}",
        'sending_response': "📤 Отправка ответа на {target}",
        'response_sent': "✅ Ответ успешно отправлен",
        'send_failed': "❌ Не удалось отправить сообщение: {error}",
        'lock_acquired': "🔒 Получена блокировка обработки",
        'lock_released': "🔓 Блокировка обработки снята",

        'packet_missing_decoded': "⚠️ В пакете отсутствует поле 'decoded'",
        'node_name': "👤 Узел {node_id} имя: {long_name}",
        'node_info_type_warning': "⚠️ Информация об узле {node_id} не является словарём",
        'broadcast_message_received': "📢 Трансляция от {from_id}{name_info}: {short_text}",
        'private_message_received': "📩 Личное сообщение от {from_id}{name_info}: {short_text}",
        'rssi_debug': "📶 RSSI: {rssi} дБм",
        'snr_debug': "🔊 SNR: {snr} дБ",
        'position_received': "📍 Получено местоположение от {from_id}",
        'detailed_position': "Подробное местоположение: {lat:.6f}, {lon:.6f}",
        'missing_from_field': "❌ Отсутствует поле 'from'",
        'position_data_empty': "⚠️ Данные о местоположении пусты",
        'missing_lat_lon': "❌ Отсутствуют широта и долгота",
        'mention_detected': "🎯 Обнаружено упоминание, будет дан ответ на трансляцию",
        'question_detected': "❓ Обнаружен вопрос, будет дан ответ на трансляцию",
        'keyword_detected': "🔍 Обнаружено ключевое слово '{keyword}', будет дан ответ на трансляцию",
        'ignore_broadcast': "⏭️ Трансляция проигнорирована (условия ответа не выполнены)",
        'ai_broadcast_response': "🤖 Ответ ИИ на трансляцию: {response}",
        'ai_private_response': "🤖 Ответ ИИ на личное сообщение: {response}",
        'ai_processing_failed': "❌ Сбой обработки ИИ: {error_msg}",
        'message_processing_error': "❌ Ошибка обработки сообщения: {error}",
        'broadcast_settings_updated': "🔄 Настройки трансляции: {status}",
        'keywords_updated': "🔄 Обновлены ключевые слова для трансляции: {keywords}",
        'processing_failed': "❌ Сбой обработки: {error_msg}",
        'processing_exception': "❌ Исключение при обработке, повторите попытку позже",
        'unknown': "Неизвестно",
        'unknown_type': "Неизвестный тип",
        'unknown_error': "Неизвестная ошибка",
        'enabled': "Включено",
        'disabled': "Отключено",
        'other_message': "Другое сообщение"
    }
}